In [ ]:
import pandas as pd
from pathlib import Path

# Définir les chemins
PROJECT_ROOT = Path("..").resolve()
DATA_PROCESSED = PROJECT_ROOT / "data" / "processed"
DATA_OUTPUTS = PROJECT_ROOT / "data" / "outputs"

# Chargement des données nettoyées
df = pd.read_csv(DATA_PROCESSED / "processed_data.csv")

# Sélection des colonnes pertinentes pour le profilage
cols_profil = [
    "enseignant_uid", "age", "statut_administratif", "etablissement",
    "annees_experience_totale", "nb_pays_enseignes", "nb_etablissements_carriere",
    "annees_enseignement_france", "annees_enseignement_mlf", "annees_enseignement_aefe",
    "formation_initiale", "certifications_educatives", "responsabilites_complementaires",
    "encadrement_formations", "formation_continue_12mois", "competences_dev_formations",
    "niveaux_enseignement", "matieres_niveaux_actuels", "nb_classes", "nb_eleves",
    "charge_travail_hors_classe", "frequence_outils_numeriques",
    "frequence_projets_interdisciplinaires", "frequence_collaboration_collegues",
    "outils_collaboration", "nb_evaluations_sequence", "adaptation_eval_ebep"
]

# Création du DataFrame
df_profils = df[cols_profil].copy()

# Ajout d'exemples de colonnes dérivées
df_profils["tranche_age"] = pd.cut(df_profils["age"], bins=[0, 30, 40, 50, 60, 100],
                                   labels=["<30", "30-40", "40-50", "50-60", "60+"])

df_profils["exp_mlf_10plus"] = df_profils["annees_enseignement_mlf"] >= 10
df_profils["a_certifications"] = df_profils["certifications_educatives"].notna() & (df_profils["certifications_educatives"] != "")

# Export
df_profils.to_csv(DATA_OUTPUTS / "df_profils.csv", index=False)

# Aperçu
print("✅ df_profils exporté avec", df_profils.shape[0], "enseignants et", df_profils.shape[1], "variables")
df_profils.head()

✅ df_profils exporté avec 3 enseignants et 30 variables

,enseignant_uid,age,statut_administratif,etablissement,annees_experience_totale,nb_pays_enseignes,nb_etablissements_carriere,annees_enseignement_france,annees_enseignement_mlf,annees_enseignement_aefe,...,charge_travail_hors_classe,frequence_outils_numeriques,frequence_projets_interdisciplinaires,frequence_collaboration_collegues,outils_collaboration,nb_evaluations_sequence,adaptation_eval_ebep,tranche_age,exp_mlf_10plus,a_certifications
0,E0001,38,Contrat local,Lycée Français International Le Détroit Tanger,16,1,6,0,6,0,...,3,2,3,4,oui,3,3,30-40,False,True
1,E0002,49,Détachement,Lycée Français International André Malraux Rabat,20,1,3,1,19,1,...,4,4,1,4,oui,2,4,40-50,True,True
2,E0003,46,Contrat local,Lycée Français International André Malraux Rabat,22,2,4,20,20,0,...,3,3,2,4,oui,12,4,40-50,True,True